framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            recipients: # destinataires
                - '%env(MAILER_SENDER_EMAIL)%'  # POUR ENVOYER LES MAILS TOUJOUS A CETTE ADRESSE
