twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']


    paths:
        #  '%kernel.project_dir%/assets/images': images  # pour pointer vers une images que l'on veut mettre dans le mail qu'on envoie; pas obligatoire juste pour le fun
        '%kernel.project_dir%/public/images': images  # pour pointer vers une images que l'on veut mettre dans le mail qu'on envoie; pas obligatoire juste pour le fun
