easy_admin: 
  entities:
         Post:
          class: App\Entity\Post
          list:
            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                # item_permission: [ROLE_ADMIN]
                # title: "Most recent Post"
                # max_results: 5
                # fields:
                #     - title
                #     - {property: 'image', type: 'image', base_path:}
                #     - content
                #     - createdAt
                #     - author
                #     - section
                #     - image
                #     - comments
                #     - categorie

                  